platform :ios, '7.0'
source 'https://github.com/apping/Hemsida24-Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

# Don’t inhibit all warnings for all pods… do it individually.  We need the editor
# POD to show all warnings.

target 'EditorDemo' do
  pod 'WordPress-iOS-Editor', :path => '../'
  pod 'UIAlertView+Blocks', '~>0.8.1', :inhibit_warnings => true
end

target "EditorDemoTests" do
    
end

